version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: orderms-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: orderms-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongo_data: